import { defineStore } from 'pinia'

export const useFinacialStore = defineStore('finacial', () => {
  const data = ref([
    {
      avgRate: 2.2,
      basicInvestAmount: 100,
      buyPurchase: 0,
      classify: '0',
      createTime: '2023-03-09 16:19:56',
      days: '3',
      defaultOdds: 1,
      icon: 'https://echo-res.oss-cn-hongkong.aliyuncs.com/oanda515b877155f74d809c4d8475c3520842.png',
      id: 13,
      level: 0,
      limitMax: 100000,
      limitMin: 1000,
      problem: '',
      process: 100,
      prodectIntroduction:
        '2月6号凌晨3点，土耳其东南部与叙利亚接壤地区爆发宛式\r\n规模7.8级地震，且后续余震不断，无数民众只能在睡梦中\r\n惊慌逃窜，再加上倒塌的建筑物四射，场景宛如噩梦般，是\r\n土耳继1999年（伊滋米特大地震）以来伤亡最为惨重的震灾\r\n。目前多国皆派出救援队前往震灾。目前多国皆派出救援队\r\n前往救灾，但由于大量断横残壁和天候不佳，与同样受到的\r\n叙利亚长年内战所致，让人道救援变得极其不便，总上网人\r\nz至少有逾4千万人，而数字仍然在持续攀升，世卫欧洲区\r\n高级紧急事务官史摩伍德会更预估最后伤亡数会是出奇报告\r\n的8倍，也就是会有至少2万人遇难，在自然灾害区土耳其东\r\n南部与叙利亚接壤地区爆发宛式规模7.8级地震，且后续余震\r\n不断，无数民众只能在睡梦中惊慌逃窜，再加上倒塌的建筑\r\n物四射，场景宛如噩梦般，是土耳继1999年（伊滋米特大地\r\n震）以来伤亡最为惨重的震灾。目前多国皆派出救援队前往\r\n震灾。目前多国皆派出救援队前往救灾，但由于大量断横残\r\n壁和天候不佳，与同样受到的叙利亚长年内战所致，让人道\r\n救援变得极其不便，总上网人数至少有逾4千万人，而数字\r\n仍然在持续攀升，世卫欧洲区高级紧急事务官史摩伍德会更\r\n预估最后伤亡数会是出奇报告的8倍，也就是会有至少2万人\r\n遇难。',
      remainAmount: 0,
      remark: '理财1-普通产品',
      sort: 1,
      status: 1,
      timeLimit: 3,
      title: 'VRRB LABS',
      totalInvestAmount: 10000000,
    },
    {
      avgRate: 2.4,
      basicInvestAmount: 100,
      buyPurchase: 0,
      classify: '0',
      createTime: '2023-03-09 16:36:27',
      days: '30',
      defaultOdds: 3,
      icon: 'https://echo-res.oss-cn-hongkong.aliyuncs.com/oandacc57246e4e924a7282fb9088dab47026.png',
      id: 14,
      level: 1,
      limitMax: 300000,
      limitMin: 100000,
      problem: '',
      process: 100,
      prodectIntroduction:
        '以太坊网络采用工作量证明（POW、Proof Of Work）形式，也就是计算机“挖矿”行为，进行以太坊网络交易的账本记账。去中心化，就是指以太坊网络把服务器分布在全球无数个计算机挖矿节点中，没有第三方权威机构对各方信用进行背书的行为，而不是像传统金融系统一样，依赖机构、公司统一拥有，统一管理的中心化服务器处理交易数据。\r\n以太坊 2021 年 6 月 28 日价格约 2050 美元。以太坊总量随时间线性增长，2021 年6 月已经挖出 1.15 亿个左右，在价格达到 4000 美元左右时以太坊曾一度逼近 5000 亿美金市值。\r\n每一个以太坊区块的产生难度通过算法动态调节，确保大约每 13 秒产出一个新区块。每个区块与上一个区块相连接，按照循序形成链条，即是区块链。每一个区块中记录的内容包括上一个区块的编号、区块产出的时间、交易笔数等不可修改的信息。截至2021 年 6 月 28 日 17:16:28，最新的区块是 Block 12721665，最终所有的区块都能溯源到 2015 年 7 月 30 日的创世区块中，以太坊历史上所有的交易都存在这一百二十多个区块的链条中。',
      remainAmount: 0,
      remark: 'Eth 依托智能合约',
      sort: 2,
      status: 1,
      timeLimit: 1,
      title: 'USDT ETH transaction',
      totalInvestAmount: 10000000,
    },
    {
      avgRate: 2.2,
      basicInvestAmount: 100,
      buyPurchase: 0,
      classify: '0',
      createTime: '2023-03-09 16:19:56',
      days: '3',
      defaultOdds: 1,
      icon: 'https://echo-res.oss-cn-hongkong.aliyuncs.com/oanda515b877155f74d809c4d8475c3520842.png',
      id: 13,
      level: 0,
      limitMax: 100000,
      limitMin: 1000,
      problem: '',
      process: 100,
      prodectIntroduction:
        '2月6号凌晨3点，土耳其东南部与叙利亚接壤地区爆发宛式\r\n规模7.8级地震，且后续余震不断，无数民众只能在睡梦中\r\n惊慌逃窜，再加上倒塌的建筑物四射，场景宛如噩梦般，是\r\n土耳继1999年（伊滋米特大地震）以来伤亡最为惨重的震灾\r\n。目前多国皆派出救援队前往震灾。目前多国皆派出救援队\r\n前往救灾，但由于大量断横残壁和天候不佳，与同样受到的\r\n叙利亚长年内战所致，让人道救援变得极其不便，总上网人\r\nz至少有逾4千万人，而数字仍然在持续攀升，世卫欧洲区\r\n高级紧急事务官史摩伍德会更预估最后伤亡数会是出奇报告\r\n的8倍，也就是会有至少2万人遇难，在自然灾害区土耳其东\r\n南部与叙利亚接壤地区爆发宛式规模7.8级地震，且后续余震\r\n不断，无数民众只能在睡梦中惊慌逃窜，再加上倒塌的建筑\r\n物四射，场景宛如噩梦般，是土耳继1999年（伊滋米特大地\r\n震）以来伤亡最为惨重的震灾。目前多国皆派出救援队前往\r\n震灾。目前多国皆派出救援队前往救灾，但由于大量断横残\r\n壁和天候不佳，与同样受到的叙利亚长年内战所致，让人道\r\n救援变得极其不便，总上网人数至少有逾4千万人，而数字\r\n仍然在持续攀升，世卫欧洲区高级紧急事务官史摩伍德会更\r\n预估最后伤亡数会是出奇报告的8倍，也就是会有至少2万人\r\n遇难。',
      remainAmount: 0,
      remark: '理财1-普通产品',
      sort: 1,
      status: 1,
      timeLimit: 3,
      title: 'VRRB LABS',
      totalInvestAmount: 10000000,
    },
    {
      avgRate: 2.4,
      basicInvestAmount: 100,
      buyPurchase: 0,
      classify: '0',
      createTime: '2023-03-09 16:36:27',
      days: '30',
      defaultOdds: 3,
      icon: 'https://echo-res.oss-cn-hongkong.aliyuncs.com/oandacc57246e4e924a7282fb9088dab47026.png',
      id: 14,
      level: 1,
      limitMax: 300000,
      limitMin: 100000,
      problem: '',
      process: 100,
      prodectIntroduction:
        '以太坊网络采用工作量证明（POW、Proof Of Work）形式，也就是计算机“挖矿”行为，进行以太坊网络交易的账本记账。去中心化，就是指以太坊网络把服务器分布在全球无数个计算机挖矿节点中，没有第三方权威机构对各方信用进行背书的行为，而不是像传统金融系统一样，依赖机构、公司统一拥有，统一管理的中心化服务器处理交易数据。\r\n以太坊 2021 年 6 月 28 日价格约 2050 美元。以太坊总量随时间线性增长，2021 年6 月已经挖出 1.15 亿个左右，在价格达到 4000 美元左右时以太坊曾一度逼近 5000 亿美金市值。\r\n每一个以太坊区块的产生难度通过算法动态调节，确保大约每 13 秒产出一个新区块。每个区块与上一个区块相连接，按照循序形成链条，即是区块链。每一个区块中记录的内容包括上一个区块的编号、区块产出的时间、交易笔数等不可修改的信息。截至2021 年 6 月 28 日 17:16:28，最新的区块是 Block 12721665，最终所有的区块都能溯源到 2015 年 7 月 30 日的创世区块中，以太坊历史上所有的交易都存在这一百二十多个区块的链条中。',
      remainAmount: 0,
      remark: 'Eth 依托智能合约',
      sort: 2,
      status: 1,
      timeLimit: 1,
      title: 'USDT ETH transaction',
      totalInvestAmount: 10000000,
    },
    {
      avgRate: 2.5,
      basicInvestAmount: 100000,
      buyPurchase: 0,
      classify: '0',
      createTime: '2023-03-09 16:43:04',
      days: '15',
      defaultOdds: 2,
      icon: 'https://echo-res.oss-cn-hongkong.aliyuncs.com/oanda885b1c7b69db44a2b681665531fa92da.png',
      id: 15,
      level: 3,
      limitMax: 1000000,
      limitMin: 200000,
      problem: '',
      process: 99,
      prodectIntroduction:
        '2月6号凌晨3点，土耳其东南部与叙利亚接壤地区爆发宛式\r\n规模7.8级地震，且后续余震不断，无数民众只能在睡梦中\r\n惊慌逃窜，再加上倒塌的建筑物四射，场景宛如噩梦般，是\r\n土耳继1999年（伊滋米特大地震）以来伤亡最为惨重的震灾\r\n。目前多国皆派出救援队前往震灾。目前多国皆派出救援队\r\n前往救灾，但由于大量断横残壁和天候不佳，与同样受到的\r\n叙利亚长年内战所致，让人道救援变得极其不便，总上网人\r\nz至少有逾4千万人，而数字仍然在持续攀升，世卫欧洲区\r\n高级紧急事务官史摩伍德会更预估最后伤亡数会是出奇报告\r\n的8倍，也就是会有至少2万人遇难，在自然灾害区土耳其东\r\n南部与叙利亚接壤地区爆发宛式规模7.8级地震，且后续余震\r\n不断，无数民众只能在睡梦中惊慌逃窜，再加上倒塌的建筑\r\n物四射，场景宛如噩梦般，是土耳继1999年（伊滋米特大地\r\n震）以来伤亡最为惨重的震灾。目前多国皆派出救援队前往\r\n震灾。目前多国皆派出救援队前往救灾，但由于大量断横残\r\n壁和天候不佳，与同样受到的叙利亚长年内战所致，让人道\r\n救援变得极其不便，总上网人数至少有逾4千万人，而数字\r\n仍然在持续攀升，世卫欧洲区高级紧急事务官史摩伍德会更\r\n预估最后伤亡数会是出奇报告的8倍，也就是会有至少2万人\r\n遇难。',
      remainAmount: 100000,
      remark: '低风险高回报',
      sort: 3,
      status: 1,
      timeLimit: 2,
      title: 'Kolibrio',
      totalInvestAmount: 10000000,
    },
    {
      avgRate: 2.7,
      basicInvestAmount: 3777779,
      buyPurchase: 0,
      classify: '0',
      createTime: '2023-03-09 16:50:05',
      days: '60',
      defaultOdds: 3333,
      icon: 'https://echo-res.oss-cn-hongkong.aliyuncs.com/oandabcee9aa68a02401087c2aae3dd8d5ec4.png',
      id: 16,
      level: 0,
      limitMax: 2000000,
      limitMin: 300000,
      problem: '',
      process: 96.09,
      prodectIntroduction:
        '2月6号凌晨3点，土耳其东南部与叙利亚接壤地区爆发宛式\r\n规模7.8级地震，且后续余震不断，无数民众只能在睡梦中\r\n惊慌逃窜，再加上倒塌的建筑物四射，场景宛如噩梦般，是\r\n土耳继1999年（伊滋米特大地震）以来伤亡最为惨重的震灾\r\n。目前多国皆派出救援队前往震灾。目前多国皆派出救援队\r\n前往救灾，但由于大量断横残壁和天候不佳，与同样受到的\r\n叙利亚长年内战所致，让人道救援变得极其不便，总上网人\r\nz至少有逾4千万人，而数字仍然在持续攀升，世卫欧洲区\r\n高级紧急事务官史摩伍德会更预估最后伤亡数会是出奇报告\r\n的8倍，也就是会有至少2万人遇难，在自然灾害区土耳其东\r\n南部与叙利亚接壤地区爆发宛式规模7.8级地震，且后续余震\r\n不断，无数民众只能在睡梦中惊慌逃窜，再加上倒塌的建筑\r\n物四射，场景宛如噩梦般，是土耳继1999年（伊滋米特大地\r\n震）以来伤亡最为惨重的震灾。目前多国皆派出救援队前往\r\n震灾。目前多国皆派出救援队前往救灾，但由于大量断横残\r\n壁和天候不佳，与同样受到的叙利亚长年内战所致，让人道\r\n救援变得极其不便，总上网人数至少有逾4千万人，而数字\r\n仍然在持续攀升，世卫欧洲区高级紧急事务官史摩伍德会更\r\n预估最后伤亡数会是出奇报告的8倍，也就是会有至少2万人\r\n遇难。',
      remainAmount: 195565,
      remark: '稳健投资超高利率',
      status: 1,
      timeLimit: 3,
      title: 'FOMO pay',
      totalInvestAmount: 5000000,
    },
  ])
  const searchValue = ref('')
  const finacialData = ref([])

  watchEffect(() => {
    finacialData.value = data.value.filter((item) =>
      item.title.includes(searchValue.value.toLocaleUpperCase() || searchValue.value),
    )
  })

  return {
    finacialData,
    searchValue,
  }
})
