export default {
  banner1: {
    'de-at': `XAUT ist eine auf Gold basierende Kryptowährung, die darauf abzielt, den Wert von Gold mit der Blockchain-Technologie zu verbinden, sodass Investoren Gold in Form von Kryptowährung halten können.`,
    'en-us': `XAUT is a gold-backed Crypto aimed at combining the value of gold with blockchain technology, allowing investors to hold gold in the form of Crypto`,
    'fr-fr': `XAUT est une cryptomonnaie adossée à l'or qui vise à combiner la valeur de l'or avec la technologie blockchain, permettant aux investisseurs de détenir de l'or sous forme de cryptomonnaie.`,
    'ja-jp': `XAUTは金に裏付けられた暗号通貨であり、金の価値をブロックチェーン技術と融合させ、投資家が暗号通貨の形式で金を保有できるようにすることを目的としています。`,
    'ko-kr': `XAUT는 금 기반 암호화폐로, 금의 가치를 블록체인 기술과 결합하여 투자자가 암호화폐 형태로 금을 보유할 수 있도록 하는 것을 목표로 합니다.`,
    'ru-ru': `XAUT — это криптовалюта, обеспеченная золотом, которая нацелена на объединение стоимости золота с технологией блокчейн, позволяя инвесторам держать золото в форме криптовалюты.`,
    'vi-vn': `XAUT là một loại tiền điện tử được hỗ trợ bằng vàng, nhằm kết hợp giá trị của vàng với công nghệ blockchain, cho phép nhà đầu tư nắm giữ vàng dưới dạng tiền điện tử.`,
    'zh-tw': `XAUT 是一種基於黃金的加密貨幣，它的目標是將黃金的價值與區塊鏈技術結合，使投資者可以通過加密貨幣的形式持有黃金。`,
    'th-th': `XAUT เป็นสกุลเงินดิจิทัลที่ได้รับการสนับสนุนโดยทองคำ มีเป้าหมายเพื่อผสานมูลค่าของทองคำเข้ากับเทคโนโลยีบล็อกเชน ทำให้นักลงทุนสามารถถือทองคำในรูปแบบสกุลเงินดิจิทัลได้`,
    'it-it': `XAUT è una criptovaluta basata sull'oro che mira a combinare il valore dell'oro con la tecnologia blockchain, consentendo agli investitori di detenere oro sotto forma di criptovaluta.`,
    'zh-cn': `XAUT 是一种基于黄金的加密货币，它的目标是将黄金的价值与区块链技术结合，使投资者可以通过加密货币的形式持有黄金。`,
    'es-us': `XAUT es una criptomoneda respaldada por oro que tiene como objetivo combinar el valor del oro con la tecnología blockchain, permitiendo a los inversores mantener oro en forma de criptomoneda.`,
    'tr-tr': `XAUT, altın destekli bir kripto para birimidir ve altının değerini blok zinciri teknolojisiyle birleştirerek yatırımcıların altını kripto para biçiminde tutmasını sağlamayı amaçlar.`,
    'hi-in': `XAUT is a gold-backed Crypto aimed at combining the value of gold with blockchain technology, allowing investors to hold gold in the form of Crypto`,
    'hu-hu': `Az XAUT egy aranyalapú kriptovaluta, amelynek célja, hogy az arany értékét ötvözze a blokklánc technológiával, lehetővé téve a befektetők számára, hogy aranyat tartsanak kriptovaluta formájában.`,
    'nl-nl': `XAUT is een op goud gebaseerde cryptovaluta die tot doel heeft de waarde van goud te combineren met blockchaintechnologie, zodat investeerders goud kunnen bezitten in de vorm van cryptocurrency.`,
    'pl-pl': `XAUT to kryptowaluta oparta na złocie, której celem jest połączenie wartości złota z technologią blockchain, umożliwiając inwestorom posiadanie złota w formie kryptowaluty.`,
    'ro-ro': `XAUT este o criptomonedă bazată pe aur, al cărei scop este să combine valoarea aurului cu tehnologia blockchain, oferind investitorilor posibilitatea de a deține aur sub formă de criptomonedă.`,
  },
  banner2: {
    'de-at': `BTC ist eine dezentrale digitale Währung, die nicht auf traditionelle Banken und Finanzinstitute angewiesen ist, sondern mithilfe der Blockchain-Technologie weltweit Transaktionen und Überweisungen durchführt.`,
    'en-us': `(BTC) is a decentralized digital currency that does not rely on traditional banks and financial institutions but instead operates globally through blockchain technology for transactions and transfers`,
    'fr-fr': `Le BTC est une monnaie numérique décentralisée qui ne dépend pas des banques et institutions financières traditionnelles, mais utilise la technologie blockchain pour effectuer des transactions et des transferts à l'échelle mondiale.`,
    'ja-jp': `BTC（ビットコイン）は、従来の銀行や金融機関に依存せず、ブロックチェーン技術を利用して世界中で取引や送金を行う分散型デジタル通貨です。`,
    'ko-kr': `BTC(비트코인)은 기존 은행 및 금융 기관에 의존하지 않고 블록체인 기술을 통해 전 세계적으로 거래 및 송금을 수행하는 분산형 디지털 통화입니다.`,
    'ru-ru': `BTC — это децентрализованная цифровая валюта, которая не зависит от традиционных банков и финансовых учреждений, а использует технологию блокчейн для осуществления транзакций и переводов по всему миру.`,
    'vi-vn': `BTC là một loại tiền kỹ thuật số phi tập trung, không phụ thuộc vào các ngân hàng và tổ chức tài chính truyền thống mà sử dụng công nghệ blockchain để thực hiện giao dịch và chuyển tiền trên phạm vi toàn cầu.`,
    'zh-tw': `(BTC) 是一種去中心化的數字貨幣，它不依賴於傳統的銀行和金融機構，而是通過區塊鏈技術在全球範圍內進行交易和轉移。`,
    'th-th': `BTC เป็นสกุลเงินดิจิทัลแบบกระจายศูนย์ที่ไม่พึ่งพาธนาคารและสถาบันการเงินแบบดั้งเดิม แต่ดำเนินการทั่วโลกผ่านเทคโนโลยีบล็อกเชนสำหรับการทำธุรกรรมและการโอนเงิน`,
    'it-it': `BTC è una valuta digitale decentralizzata che non dipende dalle banche e istituzioni finanziarie tradizionali, ma utilizza la tecnologia blockchain per effettuare transazioni e trasferimenti a livello globale.`,
    'zh-cn': `(BTC) 是一种去中心化的数字货币，不依赖传统银行和金融机构，而是通过区块链技术在全球范围内进行交易和转账。`,
    'es-us': `BTC es una moneda digital descentralizada que no depende de los bancos ni instituciones financieras tradicionales, sino que opera a nivel global mediante la tecnología blockchain para transacciones y transferencias.`,
    'tr-tr': `BTC, geleneksel bankalara ve finansal kuruluşlara bağlı olmayan, işlemler ve transferler için blok zinciri teknolojisi kullanarak dünya genelinde çalışan merkezi olmayan bir dijital para birimidir.`,
    'hi-in': `(BTC) is a decentralized digital currency that does not rely on traditional banks and financial institutions but instead operates globally through blockchain technology for transactions and transfers`,
    'hu-hu': `A BTC egy decentralizált digitális valuta, amely nem támaszkodik hagyományos bankokra és pénzintézetekre, hanem globálisan működik a blokklánc technológia révén tranzakciók és átutalások lebonyolítására.`,
    'nl-nl': `BTC is een gedecentraliseerde digitale valuta die niet afhankelijk is van traditionele banken en financiële instellingen, maar in plaats daarvan wereldwijd werkt via blockchaintechnologie voor transacties en overdrachten.`,
    'pl-pl': `BTC to zdecentralizowana waluta cyfrowa, która nie opiera się na tradycyjnych bankach i instytucjach finansowych, lecz działa globalnie dzięki technologii blockchain, umożliwiając transakcje i transfery.`,
    'ro-ro': `BTC este o monedă digitală descentralizată care nu se bazează pe bănci și instituții financiare tradiționale, ci funcționează la nivel global prin tehnologia blockchain pentru tranzacții și transferuri.`,
  },
  banner3: {
    'de-at': `Ethereum ist eine dezentralisierte Blockchain-Plattform, deren native Kryptowährung ETH (Ether) ist. Automatisierte Transaktionen und das Staking von ETH sind für Benutzer geeignet, die durch Strategien oder langfristige Investitionen Renditen erzielen möchten.`,
    'en-us': `Ethereum is a decentralized blockchain platform, and its native Crypto is ETH (Ether). Automated trading and ETH staking are suitable for users who aim to earn profits through strategies or long-term investments`,
    'fr-fr': `Ethereum est une plateforme blockchain décentralisée dont la cryptomonnaie native est l'ETH (Ether). Les transactions automatisées et le staking d'ETH conviennent aux utilisateurs cherchant à générer des rendements grâce à des stratégies ou des investissements à long terme.`,
    'ja-jp': `イーサリアム（Ethereum）は、ネイティブ暗号通貨ETH（イーサ）を持つ分散型ブロックチェーンプラットフォームです。自動取引やETHのステーキングは、戦略や長期投資を通じて収益を得たいと考えるユーザーに適しています。`,
    'ko-kr': `이더리움(Ethereum)은 ETH(이더)라는 고유 암호화폐를 사용하는 분산형 블록체인 플랫폼입니다. 자동화된 거래와 ETH 스테이킹은 전략적 또는 장기 투자로 수익을 창출하고자 하는 사용자에게 적합합니다.`,
    'ru-ru': `Ethereum — это децентрализованная блокчейн-платформа с собственной криптовалютой ETH (эфир). Автоматизированные транзакции и стейкинг ETH подходят для пользователей, стремящихся получать доход с помощью стратегий или долгосрочных инвестиций.`,
    'vi-vn': `Ethereum là một nền tảng blockchain phi tập trung với tiền điện tử gốc là ETH (Ether). Giao dịch tự động và staking ETH phù hợp với những người dùng muốn kiếm lợi nhuận thông qua các chiến lược hoặc đầu tư dài hạn.`,
    'zh-tw': `以太坊（Ethereum）是一種去中心化的區塊鏈平台，其原生加密貨幣是 ETH（以太幣）。自動化交易和 ETH 質押則適合那些希望通過策略或長期投資獲得收益的用戶。`,
    'th-th': `Ethereum เป็นแพลตฟอร์มบล็อกเชนแบบกระจายศูนย์ที่มีสกุลเงินดิจิทัลพื้นฐานคือ ETH (อีเธอร์) การทำธุรกรรมอัตโนมัติและการ Staking ETH เหมาะสำหรับผู้ใช้ที่ต้องการสร้างผลตอบแทนผ่านกลยุทธ์หรือการลงทุนระยะยาว`,
    'it-it': `Ethereum è una piattaforma blockchain decentralizzata con la sua criptovaluta nativa, ETH (Ether). Le transazioni automatizzate e lo staking di ETH sono ideali per gli utenti che cercano di ottenere rendimenti attraverso strategie o investimenti a lungo termine.`,
    'zh-cn': `以太坊（Ethereum）是一种去中心化的区块链平台，其原生加密货币是 ETH（以太币）。自动化交易和 ETH 质押则适合那些希望通过策略或长期投资获得收益的用户。`,
    'es-us': `Ethereum es una plataforma blockchain descentralizada cuya criptomoneda nativa es ETH (Ether). Las transacciones automatizadas y el staking de ETH son ideales para usuarios que buscan obtener rendimientos a través de estrategias o inversiones a largo plazo.`,
    'tr-tr': `Ethereum, yerel kripto para birimi ETH (Ether) olan merkezi olmayan bir blockchain platformudur. Otomatik işlemler ve ETH stake etme, stratejiler veya uzun vadeli yatırımlarla getiri elde etmek isteyen kullanıcılar için uygundur.`,
    'hi-in': `Ethereum is a decentralized blockchain platform, and its native Crypto is ETH (Ether). Automated trading and ETH staking are suitable for users who aim to earn profits through strategies or long-term investments`,
    'hu-hu': `Az Ethereum egy decentralizált blokkláncplatform, amelynek natív kriptovalutája az ETH (Ether). Az automatizált kereskedés és az ETH staking azoknak a felhasználóknak ideális, akik stratégiák vagy hosszú távú befektetések révén szeretnének hozamot elérni.`,
    'nl-nl': `Ethereum is een gedecentraliseerd blockchainplatform met zijn eigen cryptovaluta, ETH (Ether). Geautomatiseerde handel en ETH-staking zijn geschikt voor gebruikers die via strategieën of langetermijninvesteringen rendement willen behalen.`,
    'pl-pl': `Ethereum to zdecentralizowana platforma blockchain z natywną kryptowalutą ETH (Ether). Zautomatyzowany handel i staking ETH są odpowiednie dla użytkowników, którzy chcą osiągnąć zyski za pomocą strategii lub długoterminowych inwestycji.`,
    'ro-ro': `Ethereum este o platformă blockchain descentralizată, având criptomoneda sa nativă, ETH (Ether). Tranzacțiile automate și staking-ul ETH sunt potrivite pentru utilizatorii care doresc să obțină randamente prin strategii sau investiții pe termen lung.`,
  },
  banner4: {
    'de-at': `USDT ist das Kryptowährungssymbol von Tether, einer Stablecoin, deren Wert an traditionelle Fiat-Währungen wie den US-Dollar gekoppelt ist. Konkret bedeutet dies, dass 1 USDT in der Regel 1 US-Dollar entspricht. Das Ziel von USDT ist es, eine preisstabile Kryptowährung bereitzustellen.`,
    'en-us': `USDT is the cryptocurrency symbol for Tether, a stablecoin whose value is pegged to traditional fiat currencies such as the US dollar. Specifically, 1 USDT is typically equal to 1 USD. The goal of USDT is to provide a price-stable cryptocurrency.`,
    'fr-fr': `USDT est le symbole de la cryptomonnaie Tether, un stablecoin dont la valeur est indexée sur les monnaies fiduciaires traditionnelles comme le dollar américain. Concrètement, 1 USDT équivaut généralement à 1 USD. L'objectif de l'USDT est de fournir une cryptomonnaie stable en termes de prix.`,
    'ja-jp': `USDTはTetherの暗号通貨記号であり、Tetherは法定通貨（例：米ドル）に価値が連動しているステーブルコインです。具体的には、1 USDTは通常1ドルに相当します。USDTの目標は、価格が安定した暗号通貨を提供することです。`,
    'ko-kr': `USDT는 테더(Tether)의 암호화폐 기호이며, 테더는 전통적인 법정화폐(예: 미국 달러)에 가치를 연동한 스테이블코인입니다. 구체적으로 1 USDT는 일반적으로 1달러와 동일합니다. USDT의 목표는 가격 안정성을 가진 암호화폐를 제공하는 것입니다.`,
    'ru-ru': `USDT — это символ криптовалюты Tether, стейблкоина, стоимость которого привязана к традиционным фиатным валютам, таким как доллар США. Конкретно, 1 USDT обычно равен 1 доллару США. Цель USDT — предоставить криптовалюту с стабильной ценой.`,
    'vi-vn': `USDT là ký hiệu tiền điện tử của Tether, một stablecoin có giá trị được gắn liền với tiền pháp định truyền thống như đồng đô la Mỹ. Cụ thể, 1 USDT thường bằng 1 USD. Mục tiêu của USDT là cung cấp một loại tiền điện tử có giá ổn định.`,
    'zh-tw': `USDT 是 Tether 的加密貨幣符號，Tether 是一種穩定幣（Stablecoin），其價值與傳統法幣（如美元）掛鉤。具體來說，1 USDT 通常等於 1 美元。USDT 的目標是提供一個價格穩定的加密貨幣。`,
    'th-th': `USDT เป็นสัญลักษณ์ของสกุลเงินดิจิทัล Tether ซึ่งเป็นเหรียญ Stablecoin ที่มีมูลค่าผูกกับเงินเฟียตแบบดั้งเดิม เช่น ดอลลาร์สหรัฐ โดยเฉพาะ 1 USDT โดยทั่วไปจะเท่ากับ 1 ดอลลาร์สหรัฐ เป้าหมายของ USDT คือการมอบสกุลเงินดิจิทัลที่มีราคามั่นคง`,
    'it-it': `USDT è il simbolo della criptovaluta Tether, uno stablecoin il cui valore è ancorato a valute fiat tradizionali come il dollaro statunitense. Nello specifico, 1 USDT equivale generalmente a 1 USD. L'obiettivo di USDT è fornire una criptovaluta dal prezzo stabile.`,
    'zh-cn': `USDT 是 Tether 的加密货币符号，Tether 是一种稳定币（Stablecoin），其价值与传统法币（如美元）挂钩。具体来说，1 USDT 通常等于 1 美元。USDT 的目标是提供一个价格稳定的加密货币。`,
    'es-us': `USDT es el símbolo de la criptomoneda Tether, una stablecoin cuyo valor está vinculado a las monedas fiduciarias tradicionales, como el dólar estadounidense. Específicamente, 1 USDT generalmente equivale a 1 USD. El objetivo de USDT es proporcionar una criptomoneda con precio estable.`,
    'tr-tr': `USDT, Tether'ın kripto para birimi sembolüdür. Tether, değeri geleneksel itibari para birimlerine (örneğin, ABD Doları) sabitlenmiş bir stablecoin'dir. Özellikle, 1 USDT genellikle 1 ABD Dolarına eşittir. USDT'nin amacı, fiyat istikrarına sahip bir kripto para sağlamaktır.`,
    'hi-in': `USDT is the cryptocurrency symbol for Tether, a stablecoin whose value is pegged to traditional fiat currencies such as the US dollar. Specifically, 1 USDT is typically equal to 1 USD. The goal of USDT is to provide a price-stable cryptocurrency.`,
    'hu-hu': `A USDT a Tether kriptovaluta szimbóluma, amely egy stabilcoin, és értéke hagyományos fiat valutákhoz (például amerikai dollár) van kötve. Konkrétan 1 USDT általában 1 USD-nek felel meg. A USDT célja egy árstabil kriptovaluta biztosítása.`,
    'nl-nl': `USDT is het cryptovalutasymbool van Tether, een stablecoin waarvan de waarde is gekoppeld aan traditionele fiatvaluta's (zoals de Amerikaanse dollar). Specifiek is 1 USDT doorgaans gelijk aan 1 USD. Het doel van USDT is om een prijsstabiele cryptovaluta te bieden.`,
    'pl-pl': `USDT to symbol kryptowaluty Tether, stablecoina, którego wartość jest powiązana z tradycyjnymi walutami fiat (takimi jak dolar amerykański). Konkretne 1 USDT jest zazwyczaj równy 1 USD. Celem USDT jest zapewnienie kryptowaluty o stabilnej cenie.`,
    'ro-ro': `USDT este simbolul criptomonedei Tether, o monedă stabilă (Stablecoin) a cărei valoare este legată de valutele tradiționale (cum ar fi dolarul american). Mai exact, 1 USDT este de obicei egal cu 1 USD. Scopul USDT este de a oferi o criptomonedă cu preț stabil.`,
  },
}
